In [106]:
# Muhammed Ömer Faruk Selvi


#%%
import numpy as np

def rnd(x):
    return round(x,2)
def rndarr(arr,precision=2):
    return np.round_(arr, decimals=precision)
def prnt(mtr):
    print(mtr,"\n", rndarr(globals()[mtr], 4))



# sonlu farklar yaklaşımı ile autodiff
def derivative(f, x, y, axis=1, x_eps=0.00001, y_eps=0.0):
    results = []
    for i in range(len(y)):
        for j in range(len(y[0])):
            results.append(derivative_val(f,np.array([x[i][j]]),np.array([y[i][j]])))
    return np.array([results])

# yöntemi anlatan bir kaynak: "Scikit-Learn, Keras ve Tensorflow ile Uygulamalı Makine Öğrenmesi", Aurelien Geron, s.814
def derivative_val(f, x, y, axis=1, x_eps=0.00001, y_eps=0.0):
    return (f(x+x_eps, y+y_eps) - f(x,y))/(x_eps + y_eps)




# sigmoid aktivasyon fonksiyonu
def sigmoid(val):
    return 1.0 / (1.0 + np.exp(-val))

# sigmoid'in türevi (biri A diğeri Z için kullanılabilir)
def sigmoid_d_z(val):
    return val * (1.0 - val)

def sigmoid_d(val):
    return sigmoid(val) * (1.0 - sigmoid(val))




# mult = np.sum(np.dot(dataset_x, W_hl.T), axis=1) 
# mult2 = mult + B_hl

def loss_function_mse(y_prediction, y_truth):
    len_ = len(y_truth)
    return np.sum((y_prediction-y_truth)**2) / len_


# def loss_function_mse_d(y_prediction, y_truth):
# #     len_ = len(y_truth)
#     return (y_prediction-y_truth)

def loss_function_mse_d(y_prediction, y_truth):
    return 2*(y_prediction-y_truth)


# kaynak: https://stackoverflow.com/a/67616451
def loss_function_bce(y_truth, y_prediction):
    term_0 = (1-y_truth) * np.log(1-y_prediction + 1e-7)
    term_1 = y_truth * np.log(y_prediction + 1e-7)
    return -np.mean(term_0+term_1, axis=0)

def loss_function_bce_d(y_prediction, y_truth):
    return -(y_truth/y_prediction + 1e-7) + (1-y_truth)/(1-y_prediction + 1e-7)
# kaynak: http://neuralnetworksanddeeplearning.com/chap3.html#introducing_the_cross-entropy_cost_function
# def loss_function_bce_d(y_prediction, y_truth):
#     return derivative(loss_function_bce,y_prediction,y_truth)


def prediction(data_x, data_y):
    global Z_hl, A_hl, Z_op, A_op
    
    perceptron_value = np.dot(data_x, W_hl) + B_hl
    Pred_hl = sigmoid(perceptron_value)
    
    Z_hl = perceptron_value
    A_hl = Pred_hl

    # print(perceptron_value)
    # print(prediction)
        
#     print("W_op",W_op)
#     print("Pred_hl",Pred_hl)
    
    perceptron_value2 = np.dot(Pred_hl, W_op) + B_op
#     print("perceptron_value2",perceptron_value2)
    # Pred_op = sigmoid(perceptron_value2)
    Pred_op = perceptron_value2
    
    Z_op = perceptron_value2
    A_op = Pred_op
    prnt("A_op")
    print(data_y)
    
#     print("Loss:",loss_function_mse(Pred_op,data_y))

    


################ DATA
dataset_x = [
    [0,0],
    [0,1],
    [1,0],
    [1,1]
]

dataset_y = [
    [0,0],
    [1,1],
    [1,1],
    [0,1]
]

dataset_x = np.array(dataset_x)
dataset_y = np.array(dataset_y)

sample_count = dataset_y.shape[0]

learning_rate = 0.1

batch_size = 1 #stochastic


In [114]:
# Network 1
# Çıkışta aktivasyon yok
# Loss: MSE

print("#"*50)
print("Network 1")
print("#"*50)


# bir gizli katmanımız ve bir çıktı katmanımız var
# gizli katman 3 nöronlu; yani her bir girdi nöronundan üçer bağlantı başlar

W_hl = rndarr(np.random.random((2, 3))) # gizli katmana giden ağırlıklar
B_hl = rndarr(np.random.random((3))) # gizli katman için bias
Z_hl = np.zeros((3)) # gizli katman sonucu (inaktif)
A_hl = np.zeros((3)) # gizli katman sonucu
D_hl = np.random.random((2, 3)) # gizli katmana giden ağırlıklarının deltaları

W_op = rndarr(np.random.random((3, 2))) # çıktı katmanına giden ağırlıklar
B_op = rndarr(np.random.random((2))) # çıktı katmanı için bias
Z_op = np.zeros((2)) # çıktı katmanı sonucu (inaktif)
A_op = np.zeros((2)) # çıktı katmanı sonucu
D_op = np.random.random((3, 2)) # çıktı katmanına giden ağırlıkların deltaları

####### DATA




print("Weights and biases before starting:")
prnt("W_op")
prnt("W_hl")
prnt("B_op")
prnt("B_hl")
print("\n\n")

for epoch in range(1,51):
    print("\t Training... Epoch",epoch)
    for bno in range(0,sample_count,batch_size):
        
        print("Passing samples in the range of",bno,":",bno+batch_size)
        i_low = bno
        i_high = bno+batch_size
        if i_high > sample_count:
            i_high = sample_count
        batch_x = dataset_x[i_low:i_high]
        batch_y = dataset_y[i_low:i_high]
        # print(batch_x,batch_y,"\n\n\n")
        
    
        prediction(batch_x, batch_y)

        # print("A_op",A_op)
        # error = (batch_y[i] - A_op)**2
        error = loss_function_mse(A_op, batch_y)
        D_op = loss_function_mse_d(A_op, batch_y)
#         prnt("A_op")
#         prnt("batch_y")
#         prnt("D_op")
#         D_op = derivative(loss_function_mse,A_op, batch_y) # aynı sonucu veriyor
#         prnt("D_op")
        # prnt("delta_by")
        # print("A_hl",A_hl)
        delta_wy = np.array([np.outer(D_op[a],A_hl[a]) for a in range(len(D_op))])
        delta_wy = np.average(delta_wy,axis=0).T
        # print("delta_wy",delta_wy)
        delta_by = np.average(D_op,axis=0).T


        D_hl = np.dot(D_op, W_op.T)
        D_hl = np.multiply(D_hl, sigmoid_d(A_hl))
        # print("D_hl",D_hl)
        delta_wh = np.array([np.outer(D_hl[a],batch_x[a]) for a in range(len(D_hl))])
        delta_wh = np.average(delta_wh,axis=0).T
        # print("delta_wh",delta_wh)
        delta_bh = np.average(D_hl,axis=0).T


        # print("W_op",W_op)
        # print("W_hl",W_hl)
        # error2 = loss_function_mse(A_op, batch_y[i])
        # delta_op = np.dot(batch_x, error * sigmoid_d(A_op))


        W_op -= learning_rate * delta_wy
        W_hl -= learning_rate * delta_wh


        B_op -= learning_rate * delta_by
        B_hl -= learning_rate * delta_bh

    
    prnt("W_op")
    prnt("W_hl")
    prnt("B_op")
    prnt("B_hl")
    prediction(dataset_x, dataset_y)
    print("Loss:",loss_function_mse(A_op,dataset_y))
    print("\n")


print("\n\nDone! Final prediction result:")
prediction(dataset_x, dataset_y)
print("Loss:",loss_function_mse(A_op,dataset_y))
# print(A_op)

##################################################
Network 1
##################################################
Weights and biases before starting:
W_op 
 [[0.78 0.52]
 [0.59 0.49]
 [0.79 0.64]]
W_hl 
 [[0.13 0.93 0.37]
 [0.49 0.69 0.6 ]]
B_op 
 [0.69 0.94]
B_hl 
 [0.43 0.42 0.05]



	 Training... Epoch 1
Passing samples in the range of 0 : 1
A_op 
 [[1.9235 1.8788]]
[[0 0]]
Passing samples in the range of 1 : 2
A_op 
 [[1.3183 1.2405]]
[[1 1]]
Passing samples in the range of 2 : 3
A_op 
 [[1.1035 1.0881]]
[[1 1]]
Passing samples in the range of 3 : 4
A_op 
 [[1.2077 1.1484]]
[[0 1]]
W_op 
 [[0.3182 0.2272]
 [0.0842 0.1883]
 [0.3715 0.3864]]
W_hl 
 [[0.0988 0.9116 0.334 ]
 [0.4514 0.6661 0.5549]]
B_op 
 [-0.0206  0.4688]
B_hl 
 [ 0.2748  0.2999 -0.127 ]
A_op 
 [[0.3826 0.8871]
 [0.4797 0.9923]
 [0.4377 0.9617]
 [0.527  1.0536]]
[[0 0]
 [1 1]
 [1 1]
 [0 1]]
Loss: 0.4505633955303664


	 Training... Epoch 2
Passing samples in the range of 0 : 1
A_op 
 [[0.3826 0.8871]]
[[0 0]]
Passing sam

[[1 1]]
Passing samples in the range of 3 : 4
A_op 
 [[0.7771 1.0705]]
[[0 1]]
W_op 
 [[ 0.3461  0.178 ]
 [-0.1648  0.7181]
 [ 0.1231  0.6991]]
W_hl 
 [[-0.1171  0.9754  0.3156]
 [ 0.292   0.6767  0.661 ]]
B_op 
 [ 0.2598 -0.1188]
B_hl 
 [ 0.0411 -0.0288 -0.3903]
A_op 
 [[0.4049 0.6081]
 [0.4231 0.853 ]
 [0.3668 0.8207]
 [0.3929 1.0288]]
[[0 0]
 [1 1]
 [1 1]
 [0 1]]
Loss: 0.3691358424007246


	 Training... Epoch 41
Passing samples in the range of 0 : 1
A_op 
 [[0.4049 0.6081]]
[[0 0]]
Passing samples in the range of 1 : 2
A_op 
 [[0.2727 0.6214]]
[[1 1]]
Passing samples in the range of 2 : 3
A_op 
 [[0.5152 0.752 ]]
[[1 1]]
Passing samples in the range of 3 : 4
A_op 
 [[0.7747 1.0744]]
[[0 1]]
W_op 
 [[ 0.3486  0.1753]
 [-0.1696  0.7307]
 [ 0.118   0.7067]]
W_hl 
 [[-0.1226  0.9797  0.3177]
 [ 0.288   0.6802  0.6654]]
B_op 
 [ 0.2663 -0.13  ]
B_hl 
 [ 0.0362 -0.0373 -0.3966]
A_op 
 [[0.408  0.602 ]
 [0.4243 0.8512]
 [0.3677 0.8191]
 [0.3923 1.0309]]
[[0 0]
 [1 1]
 [1 1]
 [0 1]]
Loss: 0

In [110]:
# Network 2
# Çıkışta sigmoid var
# Loss: Binary Cross Entropy
# bir gizli katmanımız ve bir çıktı katmanımız var
# gizli katman 3 nöronlu; yani her bir girdi nöronundan üçer bağlantı başlar

print("#"*50)
print("Network 2")
print("#"*50)

W_hl = rndarr(np.random.random((2, 3))) # gizli katmana giden ağırlıklar
B_hl = np.random.random((3)) # gizli katman için bias
Z_hl = np.zeros((3)) # gizli katman sonucu (inaktif)
A_hl = np.zeros((3)) # gizli katman sonucu
D_hl = np.random.random((2, 3)) # gizli katmana giden ağırlıklarının deltaları

W_op = rndarr(np.random.random((3, 2))) # çıktı katmanına giden ağırlıklar
B_op = np.random.random((2)) # çıktı katmanı için bias
Z_op = np.zeros((2)) # çıktı katmanı sonucu (inaktif)
A_op = np.zeros((2)) # çıktı katmanı sonucu
D_op = np.random.random((3, 2)) # çıktı katmanına giden ağırlıkların deltaları

####### DATA




print("Weights and biases before starting:")
prnt("W_op")
prnt("W_hl")
prnt("B_op")
prnt("B_hl")
print("\n\n")

for epoch in range(1,51):
    print("\t Training... Epoch",epoch)
    for bno in range(0,sample_count,batch_size):
        
        print("Passing samples in the range of",bno,":",bno+batch_size)
        i_low = bno
        i_high = bno+batch_size
        if i_high > sample_count:
            i_high = sample_count
        batch_x = dataset_x[i_low:i_high]
        batch_y = dataset_y[i_low:i_high]
        # print(batch_x,batch_y,"\n\n\n")
        
    
        prediction(batch_x, batch_y)

        # print("A_op",A_op)
        # error = (batch_y[i] - A_op)**2
        error = loss_function_bce(A_op, batch_y)
#         D_op = loss_function_bce_d(A_op, batch_y)
        D_op = derivative(loss_function_bce,A_op, batch_y)
        # prnt("D_op")
        # prnt("delta_by")
        # print("A_hl",A_hl)
        delta_wy = np.array([np.outer(D_op[a],A_hl[a]) for a in range(len(D_op))])
        delta_wy = np.average(delta_wy,axis=0).T
        # print("delta_wy",delta_wy)
        delta_by = np.average(D_op,axis=0).T


        D_hl = np.dot(D_op, W_op.T)
        D_hl = np.multiply(D_hl, sigmoid_d(A_hl))
        # print("D_hl",D_hl)
        delta_wh = np.array([np.outer(D_hl[a],batch_x[a]) for a in range(len(D_hl))])
        delta_wh = np.average(delta_wh,axis=0).T
        # print("delta_wh",delta_wh)
        delta_bh = np.average(D_hl,axis=0).T


        # print("W_op",W_op)
        # print("W_hl",W_hl)
        # error2 = loss_function_mse(A_op, batch_y[i])
        # delta_op = np.dot(batch_x, error * sigmoid_d(A_op))


        W_op -= learning_rate * delta_wy
        W_hl -= learning_rate * delta_wh


        B_op -= learning_rate * delta_by
        B_hl -= learning_rate * delta_bh

    
    prnt("W_op")
    prnt("W_hl")
    prnt("B_op")
    prnt("B_hl")
    prediction(dataset_x, dataset_y)
    print("Loss:",loss_function_mse(A_op,dataset_y))
    print("\n")


print("\n\nDone! Final prediction result:")
prediction(dataset_x, dataset_y)
print("Loss:",loss_function_mse(A_op,dataset_y))
# print(A_op)
# autodiff mse için çalışıyor fakat BCE'de loss değeri patlıyor


##################################################
Network 2
##################################################
Weights and biases before starting:
W_op 
 [[0.09 0.07]
 [0.99 0.04]
 [0.52 0.73]]
W_hl 
 [[0.99 0.9  0.64]
 [0.27 0.43 0.58]]
B_op 
 [0.0329 0.013 ]
B_hl 
 [0.0939 0.5769 0.0977]



	 Training... Epoch 1
Passing samples in the range of 0 : 1
A_op 
 [[0.9867 0.4581]]
[[0 0]]
Passing samples in the range of 1 : 2
A_op 
 [[-2.2194 -2.7552]]
[[1 1]]
Passing samples in the range of 2 : 3
A_op 
 [[1.1164 0.5543]]
[[1 1]]
Passing samples in the range of 3 : 4
A_op 
 [[5.2283 4.5848]]
[[0 1]]
W_op 
 [[0.1955 2.1051]
 [0.7663 2.4767]
 [0.0873 2.9446]]
W_hl 
 [[ 1.1029  0.9614  1.2152]
 [-0.3046 -0.2697  0.4872]]
B_op 
 [0.0329 3.2367]
B_hl 
 [-0.4207 -0.1122  0.0377]
A_op 
 [[0.5166 6.74  ]
 [0.4624 6.7782]
 [0.7674 8.66  ]
 [0.7144 8.5781]]
[[0 0]
 [1 1]
 [1 1]
 [0 1]]
Loss: 49.009553712823376


	 Training... Epoch 2
Passing samples in the range of 0 : 1
A_op 
 [[0.5166 6.74  ]]
[[0

A_op 
 [[ -8.4447 451.5554]]
[[1 1]]
Passing samples in the range of 2 : 3
A_op 
 [[ -1.9974 458.0026]]
[[1 1]]
Passing samples in the range of 3 : 4
A_op 
 [[  4.4498 464.4499]]
[[0 1]]
W_op 
 [[ -0.8772 116.4634]
 [ -0.5413 116.9454]
 [ -0.6118 118.2014]]
W_hl 
 [[1298.7997 1309.4932 1337.974 ]
 [1262.1275 1272.9053 1301.3262]]
B_op 
 [3.290000e-02 1.192869e+02]
B_hl 
 [1261.4231 1272.3933 1300.5715]
A_op 
 [[ -1.9974 470.8971]
 [ -1.9974 470.8971]
 [ -1.9974 470.8971]
 [ -1.9974 470.8971]]
[[0 0]
 [1 1]
 [1 1]
 [0 1]]
Loss: 221044.97333514428


	 Training... Epoch 38
Passing samples in the range of 0 : 1
A_op 
 [[ -1.9974 470.8971]]
[[0 0]]
Passing samples in the range of 1 : 2
A_op 
 [[ -8.4447 464.4499]]
[[1 1]]
Passing samples in the range of 2 : 3
A_op 
 [[ -1.9974 470.8971]]
[[1 1]]
Passing samples in the range of 3 : 4
A_op 
 [[  4.4498 477.3443]]
[[0 1]]
W_op 
 [[ -0.8772 119.687 ]
 [ -0.5413 120.169 ]
 [ -0.6118 121.425 ]]
W_hl 
 [[1372.6144 1383.6135 1412.8903]
 [1334.9207 